update definitions and example usage
Price-Point/public-api-docs pull request #10
Opened 2022-09-02 17:54 UTC by MaxCorbel

2022-09-02 17:56 UTC, MaxCorbel commented
Not sure if I am providing too much detail/if we are actually using ISO-3166-1 alpha-2 country code format.

2022-09-02 17:59 UTC, viv32 approved these changes

2022-09-06 13:38 UTC, PhoenixAlexander-Wright approved these changes

2022-09-06 15:46 UTC, nealsiebert commented on locations.md
> +| `countryId`|int|the unique identifier of the country
we should omit countyId we don't want people relying on it and in the docs we state to to rely on undocumented api fields

2022-09-06 15:46 UTC, nealsiebert commented on locations.md
> +1. Market and port locations are used to create international moves and zip3s are used for CONUS moves.
This is only markets, ports are never used to create move

2022-09-06 15:48 UTC, nealsiebert requested changes

2022-09-06 15:48 UTC, nealsiebert commented on locations.md
> +            "countryId": 4,
omit countryId

2022-09-06 15:48 UTC, nealsiebert commented on locations.md
> +1. The mileage displays the exact distance between the input coordinates and the locations coordinates, while the extraMileage displays the distance from the input coordinates to the outermost coordi
this should be approximate distance or maybe straight line distance. Really we should just get Miranda to write this sentence for us

2022-09-13 17:30 UTC, merged